### ISSUE TITLE
Trying to execute missing method #to_hash/#to_ary

### ISSUE THREAD

**Issue by JanStevens** [phrase/phraseapp-in-context-editor-ruby#34]
We see for almost every key the following in our rails log

```
phrase: Trying to execute missing method #to_hash on key shared.sidenav_admin.main
phrase: You tried to execute the missing method #to_hash on key shared.sidenav_admin.main which is not supported. Please make sure you treat your translations as strings only.
```

In our en.yml file the key referenced looks like

```yml
shared:
  sidenav_admin:
    main: "Main"
```
In our ERB we are using
```erb
<%= t('shared.sidenav_admin.main') %>
```

Using rails 5-1-stable and ruby 2.4.2 and latest phrase app gem

**Comment by JanStevens** [comment]
A bit more context, we have a font awesome helper that uses `safe_join`

```ruby
def icon(args)
...
safe_join([args[:prefix], icon_tag, args[:suffix]].compact, ' ')
end
```
Here `args[:prefix]` and `args[:suffix]` are I18n.t translated strings

**Comment by theSoenke** [comment]
Hi, does this still occur when the font awesome helper is not used? The helper returns a string and the InContext-Editor library is expecting a translation hash. This would explain the error messages you are seeing.

As a workaround, you could blacklist the keys that use your helper method. You can [blacklist keys](https://phraseapp.com/docs/guides/working-with-phraseapp/managing-keys/#blacklisting-keys) in the web interface or ignore them in the InContext-Editor config:

`config.ignored_keys = ["number.*", "breadcrumb.*"]`

**Comment by JanStevens** [comment]
We have more then 4k translations, blacklisting keys that are used in icons is not an acceptable solution. Without the icon helper we don't have the issue but it pops up in other helpers that use the same pattern. I expect from a paying product that I don't have to go through hoops to just get it to work with my (valid) ruby code.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]) and we can take more direct action toward finding a solution.
