### ISSUE TITLE
Edit icons missing if the enabled false by default

### ISSUE THREAD

**Issue by Sysqa** [phrase/phraseapp-in-context-editor-ruby#8]
Hi,

I have a problem with the editor. The problem is when I use setup like this:
```
PhraseApp::InContextEditor.configure do |config|
  config.enabled = false
  config.project_id = PHRASEAPP_PROJECT_ID
  config.access_token = PHRASEAPP_ACCESS_TOKEN
  config.ignored_keys = ["number.*", "breadcrumb.*"]
  config.prefix = "{{__"
  config.suffix = "__}}"
end
```
and I try to enable it on my homepage then the editor is show up but the icons with the pencil are missing. So I can't click on it to edit a phrase.
I'm using Rails 3.2.19 and Ruby 2.1.6.

**Comment by docstun** [comment]
If you don't enable the In-Context Editor there won't be any edit buttons. This is intended behaviour. To enable the editor, set `config.enabled = true`.

**Comment by Sysqa** [comment]
When the `config.enabled = true` by default it working well, but I don't want to use it this way, because of some side effect e.g. show up the keys `{{__phrase.this.a.key__}}` and not the phrase in the rendered emails.

**Comment by docstun** [comment]
The editor is not meant to be used in production environment! You should only enable it when translating and always disable it in production. That's why it's disabled by default. You don't even need the Gem in your production group within the Gemfile. Instead pull the translations and ship them with your Rails app as you would normally.
